FROM python:3.12-slim

WORKDIR /code
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY shared ./shared
COPY worker ./worker

CMD ["celery", "-A", "worker.celery_app.celery_app", "worker", "--loglevel=info", "--pool=solo"]
